# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rtcrobot/Information.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Information(genpy.Message):
  _md5sum = "51b071e47da4f36ad37e1ffa8c219c91"
  _type = "rtcrobot/Information"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 imu_ax
float32 imu_ay
float32 imu_az
float32 imu_gx
float32 imu_gy
float32 imu_gz
float32 imu_mx
float32 imu_my
float32 imu_mz

float32 range_1
float32 range_2

bool    input_1
bool    input_2
bool    input_3
bool    input_4

bool    output_1
bool    output_2
bool    output_3
bool    output_4"""
  __slots__ = ['imu_ax','imu_ay','imu_az','imu_gx','imu_gy','imu_gz','imu_mx','imu_my','imu_mz','range_1','range_2','input_1','input_2','input_3','input_4','output_1','output_2','output_3','output_4']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       imu_ax,imu_ay,imu_az,imu_gx,imu_gy,imu_gz,imu_mx,imu_my,imu_mz,range_1,range_2,input_1,input_2,input_3,input_4,output_1,output_2,output_3,output_4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Information, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.imu_ax is None:
        self.imu_ax = 0.
      if self.imu_ay is None:
        self.imu_ay = 0.
      if self.imu_az is None:
        self.imu_az = 0.
      if self.imu_gx is None:
        self.imu_gx = 0.
      if self.imu_gy is None:
        self.imu_gy = 0.
      if self.imu_gz is None:
        self.imu_gz = 0.
      if self.imu_mx is None:
        self.imu_mx = 0.
      if self.imu_my is None:
        self.imu_my = 0.
      if self.imu_mz is None:
        self.imu_mz = 0.
      if self.range_1 is None:
        self.range_1 = 0.
      if self.range_2 is None:
        self.range_2 = 0.
      if self.input_1 is None:
        self.input_1 = False
      if self.input_2 is None:
        self.input_2 = False
      if self.input_3 is None:
        self.input_3 = False
      if self.input_4 is None:
        self.input_4 = False
      if self.output_1 is None:
        self.output_1 = False
      if self.output_2 is None:
        self.output_2 = False
      if self.output_3 is None:
        self.output_3 = False
      if self.output_4 is None:
        self.output_4 = False
    else:
      self.imu_ax = 0.
      self.imu_ay = 0.
      self.imu_az = 0.
      self.imu_gx = 0.
      self.imu_gy = 0.
      self.imu_gz = 0.
      self.imu_mx = 0.
      self.imu_my = 0.
      self.imu_mz = 0.
      self.range_1 = 0.
      self.range_2 = 0.
      self.input_1 = False
      self.input_2 = False
      self.input_3 = False
      self.input_4 = False
      self.output_1 = False
      self.output_2 = False
      self.output_3 = False
      self.output_4 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_11f8B().pack(_x.imu_ax, _x.imu_ay, _x.imu_az, _x.imu_gx, _x.imu_gy, _x.imu_gz, _x.imu_mx, _x.imu_my, _x.imu_mz, _x.range_1, _x.range_2, _x.input_1, _x.input_2, _x.input_3, _x.input_4, _x.output_1, _x.output_2, _x.output_3, _x.output_4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.imu_ax, _x.imu_ay, _x.imu_az, _x.imu_gx, _x.imu_gy, _x.imu_gz, _x.imu_mx, _x.imu_my, _x.imu_mz, _x.range_1, _x.range_2, _x.input_1, _x.input_2, _x.input_3, _x.input_4, _x.output_1, _x.output_2, _x.output_3, _x.output_4,) = _get_struct_11f8B().unpack(str[start:end])
      self.input_1 = bool(self.input_1)
      self.input_2 = bool(self.input_2)
      self.input_3 = bool(self.input_3)
      self.input_4 = bool(self.input_4)
      self.output_1 = bool(self.output_1)
      self.output_2 = bool(self.output_2)
      self.output_3 = bool(self.output_3)
      self.output_4 = bool(self.output_4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_11f8B().pack(_x.imu_ax, _x.imu_ay, _x.imu_az, _x.imu_gx, _x.imu_gy, _x.imu_gz, _x.imu_mx, _x.imu_my, _x.imu_mz, _x.range_1, _x.range_2, _x.input_1, _x.input_2, _x.input_3, _x.input_4, _x.output_1, _x.output_2, _x.output_3, _x.output_4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.imu_ax, _x.imu_ay, _x.imu_az, _x.imu_gx, _x.imu_gy, _x.imu_gz, _x.imu_mx, _x.imu_my, _x.imu_mz, _x.range_1, _x.range_2, _x.input_1, _x.input_2, _x.input_3, _x.input_4, _x.output_1, _x.output_2, _x.output_3, _x.output_4,) = _get_struct_11f8B().unpack(str[start:end])
      self.input_1 = bool(self.input_1)
      self.input_2 = bool(self.input_2)
      self.input_3 = bool(self.input_3)
      self.input_4 = bool(self.input_4)
      self.output_1 = bool(self.output_1)
      self.output_2 = bool(self.output_2)
      self.output_3 = bool(self.output_3)
      self.output_4 = bool(self.output_4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11f8B = None
def _get_struct_11f8B():
    global _struct_11f8B
    if _struct_11f8B is None:
        _struct_11f8B = struct.Struct("<11f8B")
    return _struct_11f8B
