// Generated by gencpp from file rtcrobot_msgs/RobotMode.msg
// DO NOT EDIT!


#ifndef RTCROBOT_MSGS_MESSAGE_ROBOTMODE_H
#define RTCROBOT_MSGS_MESSAGE_ROBOTMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rtcrobot_msgs
{
template <class ContainerAllocator>
struct RobotMode_
{
  typedef RobotMode_<ContainerAllocator> Type;

  RobotMode_()
    : code(0)
    , name()  {
    }
  RobotMode_(const ContainerAllocator& _alloc)
    : code(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _code_type;
  _code_type code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMode_

typedef ::rtcrobot_msgs::RobotMode_<std::allocator<void> > RobotMode;

typedef boost::shared_ptr< ::rtcrobot_msgs::RobotMode > RobotModePtr;
typedef boost::shared_ptr< ::rtcrobot_msgs::RobotMode const> RobotModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rtcrobot_msgs::RobotMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rtcrobot_msgs::RobotMode_<ContainerAllocator1> & lhs, const ::rtcrobot_msgs::RobotMode_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rtcrobot_msgs::RobotMode_<ContainerAllocator1> & lhs, const ::rtcrobot_msgs::RobotMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rtcrobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d02f0003881d9ef2396a7f7c3b4db158";
  }

  static const char* value(const ::rtcrobot_msgs::RobotMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd02f0003881d9ef2ULL;
  static const uint64_t static_value2 = 0x396a7f7c3b4db158ULL;
};

template<class ContainerAllocator>
struct DataType< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rtcrobot_msgs/RobotMode";
  }

  static const char* value(const ::rtcrobot_msgs::RobotMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# code of the mode\n"
"int8 code\n"
"\n"
"# name of the mode\n"
"string name\n"
;
  }

  static const char* value(const ::rtcrobot_msgs::RobotMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtcrobot_msgs::RobotMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rtcrobot_msgs::RobotMode_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.code);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTCROBOT_MSGS_MESSAGE_ROBOTMODE_H
