(cl:in-package rtcrobot-msg)
(cl:export '(IMU_AX-VAL
          IMU_AX
          IMU_AY-VAL
          IMU_AY
          IMU_AZ-VAL
          IMU_AZ
          IMU_GX-VAL
          IMU_GX
          IMU_GY-VAL
          IMU_GY
          IMU_GZ-VAL
          IMU_GZ
          IMU_MX-VAL
          IMU_MX
          IMU_MY-VAL
          IMU_MY
          IMU_MZ-VAL
          IMU_MZ
          RANGE_1-VAL
          RANGE_1
          RANGE_2-VAL
          RANGE_2
          INPUT_1-VAL
          INPUT_1
          INPUT_2-VAL
          INPUT_2
          INPUT_3-VAL
          INPUT_3
          INPUT_4-VAL
          INPUT_4
          OUTPUT_1-VAL
          OUTPUT_1
          OUTPUT_2-VAL
          OUTPUT_2
          OUTPUT_3-VAL
          OUTPUT_3
          OUTPUT_4-VAL
          OUTPUT_4
))