; Auto-generated. Do not edit!


(cl:in-package rtcrobot_actions-msg)


;//! \htmlinclude SaveMapFeedback.msg.html

(cl:defclass <SaveMapFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SaveMapFeedback (<SaveMapFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SaveMapFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SaveMapFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rtcrobot_actions-msg:<SaveMapFeedback> is deprecated: use rtcrobot_actions-msg:SaveMapFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SaveMapFeedback>) ostream)
  "Serializes a message object of type '<SaveMapFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SaveMapFeedback>) istream)
  "Deserializes a message object of type '<SaveMapFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SaveMapFeedback>)))
  "Returns string type for a message object of type '<SaveMapFeedback>"
  "rtcrobot_actions/SaveMapFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SaveMapFeedback)))
  "Returns string type for a message object of type 'SaveMapFeedback"
  "rtcrobot_actions/SaveMapFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SaveMapFeedback>)))
  "Returns md5sum for a message object of type '<SaveMapFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SaveMapFeedback)))
  "Returns md5sum for a message object of type 'SaveMapFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SaveMapFeedback>)))
  "Returns full string definition for message of type '<SaveMapFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SaveMapFeedback)))
  "Returns full string definition for message of type 'SaveMapFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SaveMapFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SaveMapFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SaveMapFeedback
))
