; Auto-generated. Do not edit!


(cl:in-package rtcrobot_actions-msg)


;//! \htmlinclude SaveMapGoal.msg.html

(cl:defclass <SaveMapGoal> (roslisp-msg-protocol:ros-message)
  ((map_name
    :reader map_name
    :initarg :map_name
    :type cl:string
    :initform ""))
)

(cl:defclass SaveMapGoal (<SaveMapGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SaveMapGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SaveMapGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rtcrobot_actions-msg:<SaveMapGoal> is deprecated: use rtcrobot_actions-msg:SaveMapGoal instead.")))

(cl:ensure-generic-function 'map_name-val :lambda-list '(m))
(cl:defmethod map_name-val ((m <SaveMapGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rtcrobot_actions-msg:map_name-val is deprecated.  Use rtcrobot_actions-msg:map_name instead.")
  (map_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SaveMapGoal>) ostream)
  "Serializes a message object of type '<SaveMapGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'map_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'map_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SaveMapGoal>) istream)
  "Deserializes a message object of type '<SaveMapGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'map_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'map_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SaveMapGoal>)))
  "Returns string type for a message object of type '<SaveMapGoal>"
  "rtcrobot_actions/SaveMapGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SaveMapGoal)))
  "Returns string type for a message object of type 'SaveMapGoal"
  "rtcrobot_actions/SaveMapGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SaveMapGoal>)))
  "Returns md5sum for a message object of type '<SaveMapGoal>"
  "25e928a2d4ff388c294895b7af935978")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SaveMapGoal)))
  "Returns md5sum for a message object of type 'SaveMapGoal"
  "25e928a2d4ff388c294895b7af935978")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SaveMapGoal>)))
  "Returns full string definition for message of type '<SaveMapGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Save Map to file~%# Specify an (optional) name for the map~%string map_name~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SaveMapGoal)))
  "Returns full string definition for message of type 'SaveMapGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Save Map to file~%# Specify an (optional) name for the map~%string map_name~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SaveMapGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'map_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SaveMapGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SaveMapGoal
    (cl:cons ':map_name (map_name msg))
))
