// Generated by gencpp from file rtcrobot_actions/MissionResult.msg
// DO NOT EDIT!


#ifndef RTCROBOT_ACTIONS_MESSAGE_MISSIONRESULT_H
#define RTCROBOT_ACTIONS_MESSAGE_MISSIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rtcrobot_actions
{
template <class ContainerAllocator>
struct MissionResult_
{
  typedef MissionResult_<ContainerAllocator> Type;

  MissionResult_()
    : done(false)  {
    }
  MissionResult_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::rtcrobot_actions::MissionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtcrobot_actions::MissionResult_<ContainerAllocator> const> ConstPtr;

}; // struct MissionResult_

typedef ::rtcrobot_actions::MissionResult_<std::allocator<void> > MissionResult;

typedef boost::shared_ptr< ::rtcrobot_actions::MissionResult > MissionResultPtr;
typedef boost::shared_ptr< ::rtcrobot_actions::MissionResult const> MissionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rtcrobot_actions::MissionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rtcrobot_actions::MissionResult_<ContainerAllocator1> & lhs, const ::rtcrobot_actions::MissionResult_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rtcrobot_actions::MissionResult_<ContainerAllocator1> & lhs, const ::rtcrobot_actions::MissionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rtcrobot_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::MissionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::MissionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::MissionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::rtcrobot_actions::MissionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rtcrobot_actions/MissionResult";
  }

  static const char* value(const ::rtcrobot_actions::MissionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"bool done\n"
;
  }

  static const char* value(const ::rtcrobot_actions::MissionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtcrobot_actions::MissionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rtcrobot_actions::MissionResult_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTCROBOT_ACTIONS_MESSAGE_MISSIONRESULT_H
