// Generated by gencpp from file rtcrobot_actions/SaveMapActionGoal.msg
// DO NOT EDIT!


#ifndef RTCROBOT_ACTIONS_MESSAGE_SAVEMAPACTIONGOAL_H
#define RTCROBOT_ACTIONS_MESSAGE_SAVEMAPACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <rtcrobot_actions/SaveMapGoal.h>

namespace rtcrobot_actions
{
template <class ContainerAllocator>
struct SaveMapActionGoal_
{
  typedef SaveMapActionGoal_<ContainerAllocator> Type;

  SaveMapActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  SaveMapActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::rtcrobot_actions::SaveMapGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapActionGoal_

typedef ::rtcrobot_actions::SaveMapActionGoal_<std::allocator<void> > SaveMapActionGoal;

typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapActionGoal > SaveMapActionGoalPtr;
typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapActionGoal const> SaveMapActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator1> & lhs, const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator1> & lhs, const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rtcrobot_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b816b9c9e8b78615543eea30ec29b0ea";
  }

  static const char* value(const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb816b9c9e8b78615ULL;
  static const uint64_t static_value2 = 0x543eea30ec29b0eaULL;
};

template<class ContainerAllocator>
struct DataType< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rtcrobot_actions/SaveMapActionGoal";
  }

  static const char* value(const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"SaveMapGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rtcrobot_actions/SaveMapGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Save Map to file\n"
"# Specify an (optional) name for the map\n"
"string map_name\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rtcrobot_actions::SaveMapActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::rtcrobot_actions::SaveMapGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTCROBOT_ACTIONS_MESSAGE_SAVEMAPACTIONGOAL_H
