// Generated by gencpp from file rtcrobot_actions/SaveMapFeedback.msg
// DO NOT EDIT!


#ifndef RTCROBOT_ACTIONS_MESSAGE_SAVEMAPFEEDBACK_H
#define RTCROBOT_ACTIONS_MESSAGE_SAVEMAPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rtcrobot_actions
{
template <class ContainerAllocator>
struct SaveMapFeedback_
{
  typedef SaveMapFeedback_<ContainerAllocator> Type;

  SaveMapFeedback_()
    {
    }
  SaveMapFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapFeedback_

typedef ::rtcrobot_actions::SaveMapFeedback_<std::allocator<void> > SaveMapFeedback;

typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapFeedback > SaveMapFeedbackPtr;
typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapFeedback const> SaveMapFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rtcrobot_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rtcrobot_actions/SaveMapFeedback";
  }

  static const char* value(const ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rtcrobot_actions::SaveMapFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RTCROBOT_ACTIONS_MESSAGE_SAVEMAPFEEDBACK_H
