// Generated by gencpp from file rtcrobot_actions/SaveMapResult.msg
// DO NOT EDIT!


#ifndef RTCROBOT_ACTIONS_MESSAGE_SAVEMAPRESULT_H
#define RTCROBOT_ACTIONS_MESSAGE_SAVEMAPRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rtcrobot_actions
{
template <class ContainerAllocator>
struct SaveMapResult_
{
  typedef SaveMapResult_<ContainerAllocator> Type;

  SaveMapResult_()
    : saved(false)  {
    }
  SaveMapResult_(const ContainerAllocator& _alloc)
    : saved(false)  {
  (void)_alloc;
    }



   typedef uint8_t _saved_type;
  _saved_type saved;





  typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapResult_

typedef ::rtcrobot_actions::SaveMapResult_<std::allocator<void> > SaveMapResult;

typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapResult > SaveMapResultPtr;
typedef boost::shared_ptr< ::rtcrobot_actions::SaveMapResult const> SaveMapResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator1> & lhs, const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator2> & rhs)
{
  return lhs.saved == rhs.saved;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator1> & lhs, const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rtcrobot_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0d3810ee720d0cb544e6a5f0d6991e9";
  }

  static const char* value(const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0d3810ee720d0cbULL;
  static const uint64_t static_value2 = 0x544e6a5f0d6991e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rtcrobot_actions/SaveMapResult";
  }

  static const char* value(const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"# Are we saved?\n"
"bool saved\n"
"\n"
;
  }

  static const char* value(const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.saved);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtcrobot_actions::SaveMapResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rtcrobot_actions::SaveMapResult_<ContainerAllocator>& v)
  {
    s << indent << "saved: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.saved);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTCROBOT_ACTIONS_MESSAGE_SAVEMAPRESULT_H
