// Auto-generated. Do not edit!

// (in-package rtcrobot_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SaveMapResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.saved = null;
    }
    else {
      if (initObj.hasOwnProperty('saved')) {
        this.saved = initObj.saved
      }
      else {
        this.saved = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SaveMapResult
    // Serialize message field [saved]
    bufferOffset = _serializer.bool(obj.saved, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SaveMapResult
    let len;
    let data = new SaveMapResult(null);
    // Deserialize message field [saved]
    data.saved = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rtcrobot_actions/SaveMapResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b0d3810ee720d0cb544e6a5f0d6991e9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    # Are we saved?
    bool saved
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SaveMapResult(null);
    if (msg.saved !== undefined) {
      resolved.saved = msg.saved;
    }
    else {
      resolved.saved = false
    }

    return resolved;
    }
};

module.exports = SaveMapResult;
